name: CI/CD - Next.js + PM2 (beh-landing)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Deploy files via rsync over SSH (with excludes)
      - name: Sync source to server (rsync)
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --exclude '.git' --exclude '.github' --exclude 'node_modules' --exclude '.next' --exclude '.env*' --exclude '.DS_Store'
          path: ./
          remote_path: ${{ secrets.APP_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Install, build, and reload via PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd "${{ secrets.APP_DIR }}"
            export $(grep -v '^#' .env.production | xargs) || true
            npm ci
            npm run build
            if pm2 list | grep -q "${{ secrets.PM2_APP_NAME }}"; then
              pm2 reload ecosystem.config.js --only "${{ secrets.PM2_APP_NAME }}"
            else
              pm2 start ecosystem.config.js
            fi
            pm2 save
